export const translations = {
    "en-US": {
        discovery: "Discovery",
        home: "Home",
        search: "Search",
        theme: "Theme",
        movies: "Movies",
        series: "Series",
        trending: "Trending",
        topRated: "Top Rated",
        upcoming: "Upcoming",
        recommendations: "Recommendations",
        cast: "Cast",
        loadingCatalog: "Loading catalog...",
        featured: "Featured",
        moreInfo: "More Info",
        all: "All",
        discoveryMovies: "Discovery Movies",
        discoverySeries: "Discovery Series",
        english: "English",
        portuguese: "Portuguese",
        spanish: "Spanish",
        french: "French",
        franch: "French",
        german: "German",
        italian: "Italian",
        japanese: "Japanese",
        kannada: "Kannada",
        chinese: "Chinese",
        notFound: "Not Found",
        itemNotFound: "Item not found",
        noResults: "No results found",
        errorLoading: "Error loading content",
        retry: "Try again",
        back: "Back",
        searchPlaceholder: "Search movies or series...",
        seeAll: "See all",
        pageNotFound: "Page not found",
    },

    "pt-BR": {
        discovery: "Descubra",
        home: "Início",
        search: "Pesquisar",
        theme: "Tema",
        movies: "Filmes",
        series: "Séries",
        trending: "Em alta",
        topRated: "Mais bem avaliados",
        upcoming: "Em breve",
        recommendations: "Recomendações",
        cast: "Elenco",
        loadingCatalog: "Carregando catálogo...",
        featured: "Em destaque",
        moreInfo: "Mais informações",
        all: "Todos",
        discoveryMovies: "Descubra filmes",
        discoverySeries: "Descubra séries",
        english: "Inglês",
        portuguese: "Português",
        spanish: "Espanhol",
        french: "Francês",
        franch: "Francês",
        german: "Alemão",
        italian: "Italiano",
        japanese: "Japonês",
        kannada: "Canarês",
        chinese: "Chinês",
        notFound: "Não encontrado",
        itemNotFound: "Item não encontrado",
        noResults: "Nenhum resultado encontrado",
        errorLoading: "Erro ao carregar o conteúdo",
        retry: "Tentar novamente",
        back: "Voltar",
        searchPlaceholder: "Pesquisar filmes ou séries...",
        seeAll: "Ver todos",
        pageNotFound: "Página não encontrada",
    },

    "es-ES": {
        discovery: "Descubre",
        home: "Inicio",
        search: "Buscar",
        theme: "Tema",
        movies: "Películas",
        series: "Series",
        trending: "Tendencias",
        topRated: "Mejor valoradas",
        upcoming: "Próximamente",
        recommendations: "Recomendaciones",
        cast: "Reparto",
        loadingCatalog: "Cargando catálogo...",
        featured: "Destacado",
        moreInfo: "Más información",
        all: "Todos",
        discoveryMovies: "Descubre películas",
        discoverySeries: "Descubre series",
        english: "Inglés",
        portuguese: "Portugués",
        spanish: "Español",
        french: "Francés",
        franch: "Francés",
        german: "Alemán",
        italian: "Italiano",
        japanese: "Japonés",
        kannada: "Canarés",
        chinese: "Chino",
        notFound: "No encontrado",
        itemNotFound: "Elemento no encontrado",
        noResults: "No se encontraron resultados",
        errorLoading: "Error al cargar el contenido",
        retry: "Intentar de nuevo",
        back: "Volver",
        searchPlaceholder: "Buscar películas o series...",
        seeAll: "Ver todo",
        pageNotFound: "Página no encontrada",
    },

    "fr-FR": {
        discovery: "Découvrir",
        home: "Accueil",
        search: "Rechercher",
        theme: "Thème",
        movies: "Films",
        series: "Séries",
        trending: "Tendances",
        topRated: "Les mieux notés",
        upcoming: "À venir",
        recommendations: "Recommandations",
        cast: "Distribution",
        loadingCatalog: "Chargement du catalogue...",
        featured: "À la une",
        moreInfo: "Plus d'informations",
        all: "Tous",
        discoveryMovies: "Découvrez des films",
        discoverySeries: "Découvrez des séries",
        english: "Anglais",
        portuguese: "Portugais",
        spanish: "Espagnol",
        french: "Français",
        franch: "Français",
        german: "Allemand",
        italian: "Italien",
        japanese: "Japonais",
        kannada: "Kannada",
        chinese: "Chinois",
        notFound: "Introuvable",
        itemNotFound: "Élément introuvable",
        noResults: "Aucun résultat trouvé",
        errorLoading: "Erreur lors du chargement du contenu",
        retry: "Réessayer",
        back: "Retour",
        searchPlaceholder: "Rechercher des films ou des séries...",
        seeAll: "Voir tout",
        pageNotFound: "Page introuvable",
    },

    "de-DE": {
        discovery: "Entdecken",
        home: "Startseite",
        search: "Suchen",
        theme: "Design",
        movies: "Filme",
        series: "Serien",
        trending: "Angesagt",
        topRated: "Am besten bewertet",
        upcoming: "Demnächst",
        recommendations: "Empfehlungen",
        cast: "Besetzung",
        loadingCatalog: "Katalog wird geladen...",
        featured: "Highlights",
        moreInfo: "Mehr Infos",
        all: "Alle",
        discoveryMovies: "Filme entdecken",
        discoverySeries: "Serien entdecken",
        english: "Englisch",
        portuguese: "Portugiesisch",
        spanish: "Spanisch",
        french: "Französisch",
        franch: "Französisch",
        german: "Deutsch",
        italian: "Italienisch",
        japanese: "Japanisch",
        kannada: "Kannada",
        chinese: "Chinesisch",
        notFound: "Nicht gefunden",
        itemNotFound: "Element nicht gefunden",
        noResults: "Keine Ergebnisse gefunden",
        errorLoading: "Fehler beim Laden des Inhalts",
        retry: "Erneut versuchen",
        back: "Zurück",
        searchPlaceholder: "Filme oder Serien suchen...",
        seeAll: "Alle anzeigen",
        pageNotFound: "Seite nicht gefunden",
    },

    "it-IT": {
        discovery: "Scopri",
        home: "Home",
        search: "Cerca",
        theme: "Tema",
        movies: "Film",
        series: "Serie TV",
        trending: "In tendenza",
        topRated: "I più votati",
        upcoming: "In arrivo",
        recommendations: "Consigliati",
        cast: "Cast",
        loadingCatalog: "Caricamento catalogo...",
        featured: "In evidenza",
        moreInfo: "Più info",
        all: "Tutti",
        discoveryMovies: "Scopri i film",
        discoverySeries: "Scopri le serie TV",
        english: "Inglese",
        portuguese: "Portoghese",
        spanish: "Spagnolo",
        french: "Francese",
        franch: "Francese",
        german: "Tedesco",
        italian: "Italiano",
        japanese: "Giapponese",
        kannada: "Kannada",
        chinese: "Cinese",
        notFound: "Non trovato",
        itemNotFound: "Elemento non trovato",
        noResults: "Nessun risultato trovato",
        errorLoading: "Errore nel caricamento del contenuto",
        retry: "Riprova",
        back: "Indietro",
        searchPlaceholder: "Cerca film o serie TV...",
        seeAll: "Vedi tutti",
        pageNotFound: "Pagina non trovata",
    },

    "ja-JP": {
        discovery: "発見",
        home: "ホーム",
        search: "検索",
        theme: "テーマ",
        movies: "映画",
        series: "ドラマ",
        trending: "トレンド",
        topRated: "高評価",
        upcoming: "公開予定",
        recommendations: "おすすめ",
        cast: "キャスト",
        loadingCatalog: "カタログを読み込み中...",
        featured: "注目の作品",
        moreInfo: "詳細情報",
        all: "すべて",
        discoveryMovies: "映画を検索",
        discoverySeries: "ドラマを検索",
        english: "英語",
        portuguese: "ポルトガル語",
        spanish: "スペイン語",
        french: "フランス語",
        franch: "フランス語",
        german: "ドイツ語",
        italian: "イタリア語",
        japanese: "日本語",
        kannada: "カンナダ語",
        chinese: "中国語",
        notFound: "見つかりません",
        itemNotFound: "アイテムが見つかりません",
        noResults: "検索結果がありません",
        errorLoading: "コンテンツの読み込みエラー",
        retry: "もう一度試す",
        back: "戻る",
        searchPlaceholder: "映画やドラマを検索...",
        seeAll: "すべて見る",
        pageNotFound: "ページが見つかりません",
    },

    "kn-IN": {
        discovery: "ಶೋಧನೆ",
        home: "ಮುಖ್ಯ ಪುಟ",
        search: "ಹುಡುಕಿ",
        theme: "ಥೀಮ್",
        movies: "ಸಿನಿಮಾಗಳು",
        series: "ಸರಣಿಗಳು",
        trending: "ಟ್ರೆಂಡಿಂಗ್",
        topRated: "ಉನ್ನತ ದರ್ಜೆಯ",
        upcoming: "ಮುಂಬರುವ",
        recommendations: "ಶಿಫಾರಸುಗಳು",
        cast: "ಪಾತ್ರವರ್ಗ",
        loadingCatalog: "ಕ್ಯಾಟಲಾಗ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
        featured: "ವಿಶೇಷ",
        moreInfo: "ಹೆಚ್ಚಿನ ಮಾಹಿತಿ",
        all: "ಎಲ್ಲಾ",
        discoveryMovies: "ಡಿಸ್ಕವರಿ ಸಿನಿಮಾಗಳು",
        discoverySeries: "ಡಿಸ್ಕವರಿ ಸರಣಿಗಳು",
        english: "ಇಂಗ್ಲಿಷ್",
        portuguese: "ಪೋರ್ಚುಗೀಸ್",
        spanish: "ಸ್ಪ್ಯಾನಿಷ್",
        french: "ಫ್ರೆಂಚ್",
        franch: "ಫ್ರೆಂಚ್",
        german: "ಜರ್ಮನ್",
        italian: "ಇಟಾಲಿಯನ್",
        japanese: "ಜಪಾನೀಸ್",
        kannada: "ಕನ್ನಡ",
        chinese: "ಚೈನೀಸ್",
        notFound: "ಸಿಗಲಿಲ್ಲ",
        itemNotFound: "ಅಂಶ ಸಿಗಲಿಲ್ಲ",
        noResults: "ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಸಿಗಲಿಲ್ಲ",
        errorLoading: "ವಿಷಯವನ್ನು ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ದೋಷ",
        retry: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
        back: "ಹಿಂತಿರುಗಿ",
        searchPlaceholder: "ಸಿನಿಮಾಗಳು ಅಥವಾ ಸರಣಿಗಳನ್ನು ಹುಡುಕಿ...",
        seeAll: "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
        pageNotFound: "ಪುಟ ಸಿಗಲಿಲ್ಲ",
    },
} as const;

export type SupportedLanguage = keyof typeof translations;
export type TranslationKey = keyof typeof translations["en-US"];