import type { Metadata } from "next";
import "./globals.css";
import TopbarPublic from "./components/TopbarPublic";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className="bg-white text-black dark:bg-slate-950 dark:text-white transition-colors duration-300">
        <TopbarPublic />
        {children}
        <Footer />
      </body>
    </html>
  );
}
